// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrKf1bNLS_JVUJDLVTE8itp-sZTvOWWJ8',
    appId: '1:633946362014:web:84b54cf1bd8526247f6b8f',
    messagingSenderId: '633946362014',
    projectId: 'turf-7440a',
    authDomain: 'turf-7440a.firebaseapp.com',
    storageBucket: 'turf-7440a.appspot.com',
    measurementId: 'G-KG0ZQJ84RJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2X4HTeMfyX8A7zDZcN1Dzn2tnblmsrPs',
    appId: '1:633946362014:android:6c8764bc626240ef7f6b8f',
    messagingSenderId: '633946362014',
    projectId: 'turf-7440a',
    storageBucket: 'turf-7440a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM7WxPal7l8XoNbiFPy9SWoJwdTSEAAiI',
    appId: '1:633946362014:ios:4c2facf2be6e5abc7f6b8f',
    messagingSenderId: '633946362014',
    projectId: 'turf-7440a',
    storageBucket: 'turf-7440a.appspot.com',
    iosBundleId: 'com.example.turfff',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM7WxPal7l8XoNbiFPy9SWoJwdTSEAAiI',
    appId: '1:633946362014:ios:4c2facf2be6e5abc7f6b8f',
    messagingSenderId: '633946362014',
    projectId: 'turf-7440a',
    storageBucket: 'turf-7440a.appspot.com',
    iosBundleId: 'com.example.turfff',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrKf1bNLS_JVUJDLVTE8itp-sZTvOWWJ8',
    appId: '1:633946362014:web:76913f3fd8549d8d7f6b8f',
    messagingSenderId: '633946362014',
    projectId: 'turf-7440a',
    authDomain: 'turf-7440a.firebaseapp.com',
    storageBucket: 'turf-7440a.appspot.com',
    measurementId: 'G-3E2F02X8H7',
  );
}
